### ISSUE TITLE
Add to Chrome webstore

### ISSUE THREAD

**Issue by christianv** [keithclark/gadebugger#1]
Would it be possible to add it to the chrome webstore?

https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna?hl=en

**Comment by colinhowells** [comment]
Yeah, I was stoked to get this going but Chrome no longer allows manual adding of extensions without going through the store: https://support.google.com/chrome_webstore/answer/2664769?p=crx_warning&rd=1 (You can't actually add it through the Extensions page, as they tell you to do.)

**Comment by keithclark** [comment]
For now, you can add GA Debugger to Chrome by browsing to `chrome://extensions/` and dragging the downloaded `gadebugger-x.x.x.crx` into the window

**Comment by colinhowells** [comment]
Ah haaaaaaaaaah ... never occurred to me to do that - works! Thank you!

**Comment by jrinconhanna** [comment]
<<For now, you can add GA Debugger to Chrome by browsing to chrome://extensions/ and dragging the downloaded gadebugger-x.x.x.crx into the window

@keithclark Tried that but getting the following error:



![screenshot 2015-05-19 10 19 53](https://cloud.githubusercontent.com/assets/6122077/7698457/a9af6ede-fe10-11e4-9173-c8b90610d5ba.png)

**Comment by keithclark** [comment]
Interesting! I see this when I drag and drop into the extensions panel:

![screen shot 2015-05-19 at 09 25 00](https://cloud.githubusercontent.com/assets/588665/7698577/45daabb4-fe09-11e4-9362-102c58755d13.png)

**Comment by jodamo5** [comment]
@keithclark Hi.  I get the same "CRX_MAGIC_NUMBER_INVALID" error as @jrinconhanna when I drag it into Chrome. To be clear, I simply downloaded the .crx file from the "dist" folder and then dragged it onto the extensions panel. Is that what I'm supposed to do? This extension looks really good, so I'm keen to give it a go.

**Comment by jrinconhanna** [comment]
@jodamo5 exactly what I did too. I also wonder if I should do something else on top @keithclark

**Comment by keithclark** [comment]
I've tried installing this on a few machines now and I'm still unable to reproduce this issue.

Could you try repeating the install process but tick "Developer Mode" in the extensions window? Also Which versions of Chrome and which OS are you using?

**Comment by jodamo5** [comment]
Hi @keithclark.  I recorded a 30 sec video of what I'm doing when I try to install it, and the error I get.  I'm just dragging the crx file onto the extensions screen in Chrome, like you mentioned.  Hopefully this will show you what we're doing wrong! http://youtu.be/NHvsrLE8XVg?hd=1

**Comment by keithclark** [comment]
Ah! I see your problem...

You can't download files from github like that. You're actually downloading the HTML content of a page on github — not the binary file. If you click that link normally you'll see the page you're downloading.

To download the correct file, follow the link and save the link to the raw content (right click on view raw and save that link). Alternatively, you could download the file from the [GA Debugger site](https://keithclark.github.io/gadebugger/).

**Comment by jodamo5** [comment]
It works!! Glad I made that video so you could see exactly what we were doing wrong.  Thanks for your help.

**Comment by jrinconhanna** [comment]
@jodamo5 Thanks for following up and @keithclark thanks for the explanation!

Now it's installed, but as I navigate, nothing seems to appear

<img width="1068" alt="screenshot 2015-07-29 17 04 11" src="https://cloud.githubusercontent.com/assets/6122077/8961159/e654b138-3613-11e5-8503-4bef3e957dd4.png">

**Comment by jodamo5** [comment]
I thought the same thing too at first @jrinconhanna.  I found that you need to click the black circle to "Start capturing", and then hit 'Refresh'.  Then then the data shows up.

**Comment by keithclark** [comment]
@jodamo5 is correct, you need to click the 'record' button before you capture data. I hoped this would be intuitive as GA Debugger follows the same UI patterns as the other tools in devtools — Looks like I need some documentation on installation and a quick "How to use" guide.

**Comment by jrinconhanna** [comment]
@jodamo5 thanks for the tip! @keithclark Haven't used that many other tools, maybe that's why I was unfamiliar with it :)

Still doesn't work for me though. Could it be httpS?
http://www.screencast.com/t/kCdGNCQflq

**Comment by jrinconhanna** [comment]
Skip that, now it works it seems. Had to take out my Mixpanel debugger off. Excited to take it for a spin!

**Comment by keithclark** [comment]
GADebugger is now available in the Chrome web store:

https://chrome.google.com/webstore/detail/gadebugger/jiokjpcfnipnicblkgdklknjjeohnfln
