### ISSUE TITLE
Get Addon signed by Firefox

### ISSUE THREAD

**Issue by irvin** [keithclark/gadebugger#11]
Addording to support article, Firefox Addon should uploaded to addon.mozilla.org for automatically test and signing, in order to keep work after Firefox 41 (around 45 days from now, current in beta). 
https://support.mozilla.org/zh-TW/kb/add-on-signing-in-firefox
https://wiki.mozilla.org/Addons/Extension_Signing

**Comment by keithclark** [comment]
Thanks for the heads-up on this, I hadn't realised Mozilla were going to lock down extensions!

As a first step I've submitted the current version to addon.mozilla.org. It's waiting for a full review which could take up to 10 days. Once review is complete I'll direct the website download link to the Mozilla Add-ons URL. 

In the mean time the extension can be found here: https://addons.mozilla.org/en-US/firefox/addon/gadebugger/

**Comment by irvin** [comment]
As my understand, you can still download the signed xpi and hosted on project's page. 
You can also make AMO page unpublished (thus the add-on won't list on AMO), so it may be just one more step after package.

**Comment by keithclark** [comment]
Yeah, that's my understanding too. Publishing to AMO will open the extension to a wider audience, so I think I'll do that too. I'll also look into publishing this to Chrome store too (despite my feelings about Google charging me a registration fee to give software away for free)

**Comment by keithclark** [comment]
GADebugger has been reviewed and is published on AMO.

https://addons.mozilla.org/en-US/firefox/addon/gadebugger/
