### ISSUE TITLE
Broken in newer versions of Firefox

### ISSUE THREAD

**Issue by robertkent87** [keithclark/gadebugger#28]
I'm using the developer edition of Firefox which is on the Aurora channel. The extension doesn't appear to display correctly in the most recent version 44.0a2 (2015-11-17).

![2015-11-17 14_56_35-google analytics debugger - firefox developer edition](https://cloud.githubusercontent.com/assets/1167648/11214949/d215dd9e-8d3b-11e5-9063-c77bd4ed6ff1.png)

Seems totally fine in the release channel though (42.0)

**Comment by keithclark** [comment]
Thanks for the report.

I am aware of this issue. The Firefox devtools team have changed all the internal paths for the devtools assets in Firefox 44, which breaks everything. I'm working on a temporary fix which should allow the extension to run correctly in both pre and post 44 releases.

Once 43 is old enough I'll make the extension require version 44 and above.

**Comment by robertkent87** [comment]
Ok, that's cool. I had heard that 43 and 44 broke a lot of stuff. It still works great in 42 and Chrome so that's a plus.

Awesome extension btw! I've ditched the old one I used to use :)

**Comment by keithclark** [comment]
Reopening this in case others notice this issue and want to add details
