### ISSUE TITLE
Not working on chrome now

### ISSUE THREAD

**Issue by jrinconhanna** [keithclark/gadebugger#29]
Was working for me before. Tried it today but to no avail. Re-installed extension but still not working for me.

**Comment by keithclark** [comment]
Can you let me know which versions of Chrome and the extension you're using? Also, is the extension from the Chrome webstore or your own build?

**Comment by jrinconhanna** [comment]
Sure.

Chrome:  47.0.2526.73 (64-bit)
Google Analytics Debugger 2.1.0

**Comment by keithclark** [comment]
Is this still an issue?

**Comment by jrinconhanna** [comment]
I'm trying this again, but it doesn't seem to work.The plugin is not lightup in chrome bar

<img width="312" alt="screenshot 2017-04-19 11 56 01" src="https://cloud.githubusercontent.com/assets/6122077/25174313/3d0843b8-24f7-11e7-8878-b311bb44c131.png">

Althought recording is on, nothing appears:

<img width="999" alt="screenshot 2017-04-19 11 56 49" src="https://cloud.githubusercontent.com/assets/6122077/25174365/6d5dadc8-24f7-11e7-8d87-f1d79ff76941.png">

Any help would be great.
