### ISSUE TITLE
Broken in Firefox 48

### ISSUE THREAD

**Issue by hazmeister** [keithclark/gadebugger#33]
It looks like the electrolysis update for Firefox has a broken a number of addons, including your awesome tool!  Any plans to patch it?  I'd offer to help, but I wouldn't know the first place to start.

**Comment by keithclark** [comment]
Yes, I am working on an update to fix GADebugger for newer versions of Firefox.

**Comment by keithclark** [comment]
Fixed in 2.1.3. You should be able to update using the Firefox Add-on Manager, or by installing the latest version from [AMO](https://addons.mozilla.org/en-US/firefox/addon/gadebugger/).

Thanks for taking the time to file a bug report.

**Comment by hazmeister** [comment]
Brill! Thanks for responding so quickly with a patch!
