### ISSUE TITLE
IP addresses not supported

### ISSUE THREAD

**Issue by stoikerty** [keithclark/gadebugger#35]
Hey @keithclark

You've got an awesome extension, I really like it, especially the little icons and how organised it looks! Thanks for the effort that has gone into making such a useful tool.

I noticed that IP addresses don't seem to work, but `localhost` does. Would it be possible to add support for IP addresses such as `http://20.20.21.184:3000/` in addition to localhost?

**Comment by keithclark** [comment]
GADebugger works by intercepting HTTP requests made to GA servers. It doesn't filter these requests by host so IP addresses should work just fine.

Here's a test I ran locally using a IP and port number:

![screen shot 2016-09-08 at 13 18 46](https://cloud.githubusercontent.com/assets/588665/18349234/246620b6-75c8-11e6-8216-54ceb9d566d7.png)

**Comment by stoikerty** [comment]
That is really strange. I use [Browsersync](https://www.browsersync.io/) as a passthrough, so it could have been related to that. I tried a few other sites, went back and when restarted browser-sync it worked.

Thanks anyway!
