### ISSUE TITLE
Plugin doesn't show any data.

### ISSUE THREAD

**Issue by ice-ivanov** [keithclark/gadebugger#36]
I have installed the plugin, restarted the browser and tested in on a couple websites i'm administrating. One of them is using GA code, another is using GTM code.
In both cases it's just a blank field, nothing appears at all.
![screen shot 12-21-16 at 04 20 pm](https://cloud.githubusercontent.com/assets/14149705/21390719/5e6ae292-c799-11e6-90e5-d0c34833850f.JPG)
Please let me know if I'm doing something wrong.

**Comment by fakhrishahab** [comment]
Have you add your site to Google Analytics?

**Comment by ice-ivanov** [comment]
I work as a web-analytic and I have to use chrome to test my websites. GA code works just fine on all my websites, it's just very unhandy that I have to use chrome to test GA and GTM events.

**Comment by keithclark** [comment]
Have you clicked the record button to start capturing data? The record icon (the solid circle) should turn red when the extension is capturing data. I ask because the screen grab above doesn't look like it's in the capture state

**Comment by ice-ivanov** [comment]
So do I have to press it every time I reload the page or open a new tab of the same website? That makes little sense. Is it possible to change that? I still have to use Chrome for this only purpose because I only have to click "GA Debug: ON" once and then it works until I turn it off or close Chrome.

**Comment by keithclark** [comment]
A separate instance of GA Debugger is created for each tab — just like every other panel in Chrome Devtools — you'll need to start capturing data in each tab you open.  Once you're capturing data, GADebugger will continue to run across page loads in the current tab. To stop capturing data, simply click the record button again.

**Comment by ice-ivanov** [comment]
Thank you.
It would be more handy if there was an option to set "record" always on for the current session or a specific domain name.
