### ISSUE TITLE
Blank window and inactive buttons in Firefox Developer Edition

### ISSUE THREAD

**Issue by TheExecutive** [keithclark/gadebugger#37]
On Firefox Developer Edition, GA Debugger is blank, doesn't match theme styling of the developer tools window, and the button to start recording events does not do anything when clicked. The checkbox can be unchecked, but does nothing. No "Preserve log" label appears next to the checkbox. No events appear when fired.

I have been able to reproduce this issue in the latest versions of both the Windows and Mac versions of Firefox Developer Edition 53.0a2 (64-bit) and on the Mac version of vanilla Firefox 51.0.1 (64-bit).

This is GA Debugger version 2.1.3. See screenshot. Thanks!

<img width="1020" alt="screen shot 2017-02-13 at 2 29 31 pm" src="https://cloud.githubusercontent.com/assets/1047778/22899528/22523ac8-f1f9-11e6-9430-b3ab37b7ba03.png">

**Comment by keithclark** [comment]
It looks like one of the devtools module paths have changed in Firefox 51. Hopefully, this will be a simple fix.

![screen shot 2017-02-13 at 21 08 05](https://cloud.githubusercontent.com/assets/588665/22903465/98423332-f230-11e6-86eb-e32bde2dd447.png)

**Comment by keithclark** [comment]
Fixed in v2.1.4. I've submitted the add-on to AMO for review. Once the review is complete you should be able to update GA debugger using the Firefox Add-on Manager, or you can install the latest version directly from [AMO](https://addons.mozilla.org/en-US/firefox/addon/gadebugger/).

Thanks for taking the time to file a bug report.

**Comment by TheExecutive** [comment]
Much appreciated. Thanks for putting in a fix so quickly.

**Comment by keithclark** [comment]
Had to hotfix the fix — v2.1.5 is now on [AMO](https://addons.mozilla.org/en-US/firefox/addon/gadebugger/) and can be updated via the Add-on Manager
