### ISSUE TITLE
WebExtensions, Firefox release

### ISSUE THREAD

**Issue by captainhook** [keithclark/gadebugger#48]
Hi,

Is there a WebExtensions port for Firefox in the works? FF 57 is nearing release; FF Nightly is currently on version 56.

**Comment by inspector71** [comment]
Update: Sorry everyone. It's working for me now. 

~~I just installed this in Firefox 54.0.1 (64-bit) and it doesn't seem to work at all.
The tab in dev tools appears, along with a toolbar. I click the (black?) record button and reload the page. Nothing whatsoever.~~

~~I guess there's a possibility of add-on conflicts or maybe an about:config tweak I've made that might conflict but I'm not convinced.~~

**Comment by keithclark** [comment]
The chrome version uses WebExtensions, have you tried installing that in FF? Last time I checked, FF hadn't implemented the devtools panel API.
