### ISSUE TITLE
Version 2.1.6 not installable in latest firefox

### ISSUE THREAD

**Issue by mbosman** [keithclark/gadebugger#49]
According to the Firefox addon manager the newest version of the addon is not installable for the newer version of Firefox
When trying to install an older version,  only version 2.1.3 is availlable but this unfixes #37 
![screen shot 2017-08-18 at 14 04 00](https://user-images.githubusercontent.com/1469918/29458276-8e8e6650-841e-11e7-8e7a-c3a8baadaf97.png)

**Comment by keithclark** [comment]
That's strange. AMO usually updates the supported version automatically. Looking at your screen grab, the supported version number appears to be decreasing.

I'm looking into create a WebExtensions version of this addon that works in all browsers. Hopefully, once that work is complete these issues will be resolved.

**Comment by keithclark** [comment]
I've updated the AMO entry for this — can you try installing the add-on again?

**Comment by mbosman** [comment]
Looks good now, thanks for looking into it!
