### ISSUE TITLE
Up to date?

### ISSUE THREAD

**Issue by cshanejennings** [keithclark/gadebugger#5]
I compiled and installed and I get the panel, but I'm seeing the below with no changes.  I've confirmed analytics beacons are going out.

![debugger](https://cloud.githubusercontent.com/assets/547913/6191394/fda55a10-b376-11e4-895c-e4e9ed6be90b.png)

Any idea on a starting point for this problem?

**Comment by keithclark** [comment]
Can you confirm that the tracking beacon URLs start with either `http://www.google-analytics.com/collect?` or `http://www.google-analytics.com/__utm.gif?`

**Comment by cshanejennings** [comment]
Ah, strange, it's sending to http://stats.g.doubleclick.net/__utm.gif  Any idea why that might be?

**Comment by keithclark** [comment]
It looks like enabling enabled the "Remarketing with Google Analytics" feature causes requests to go to `stats.g.doubleclick.net` rather than `www.google-analytics.com`. More info can be found on the [Google Analytics developer documentation](https://developers.google.com/analytics/resources/concepts/gaConceptsTrackingOverview).

Thanks for the report.

**Comment by keithclark** [comment]
If you checkout branch `005-allow-doubleclick-tracking` and rebuild the extension you should now see tracking beacons.

I've tested on a few live sites and it seems to work as expected. If this fixes your issue I'll merge it in.

**Comment by cshanejennings** [comment]
Not seeing anything, but I just thought to mention these beacons are coming from Flash, will this be captured or are they only pulled from javascript broadcasts?

**Comment by keithclark** [comment]
If the request appears in the Network tab of Chrome devtools then the extension should pick up the request and show it. Is the site available to look at online? If not, could add the full tracking beacon URL (anonymise any sensitive data) to this issue and I'll try running the test suite against it.

**Comment by keithclark** [comment]
Something else just occurred to me; is the beacon a `GET` or is flash `POST`ing it?

**Comment by cshanejennings** [comment]
Here's an example.
http://player.piksel.com/p/e190kf2d

I'm seeing the beacons in Charles, but not in the network tab.  This is probably not related to your code.

**Comment by cshanejennings** [comment]
It was my flash version (I was using the debug version).  It works!  Thanks so much!

**Comment by cshanejennings** [comment]
Oh, and it was GET.  Thanks again, this one's resolved (at least on my end)!

**Comment by keithclark** [comment]
Great!
