### ISSUE TITLE
Extension not working on firefox

### ISSUE THREAD

**Issue by melishatrout** [keithclark/gadebugger#51]
Unable to see any data pullign through to the de-bugger on my companies site

![image](https://user-images.githubusercontent.com/19528832/30366707-ef51c92e-9863-11e7-9419-3779d26712f2.png)

**Comment by keithclark** [comment]
Can I assume the extension is working as expected now?

**Comment by marcogadget** [comment]
But not in the new Firefox Quantum :-( which is A-M-A-Z-I-N-G !!! ;-)
